version: "3.8"

services:
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    environment:
      ELASTICSEARCH_HOSTS: http://search:9200
    ports:
      - "5601:5601"

networks:
  default:
    name: elastic
