apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: test-container
    image: nginx
    env:
    - name: VARIABLE_DEMO
      valueFrom:
        configMapRef:
          name: demo
          key: lab.difficulty
