apiVersion: v1
kind: Pod
spec:
  containers:
  - name: mycontainer
    image: nginx
	volumeMounts:
	- name: storagesecret
	  mountPath: "/etc/sup"
	  readOnly: true
  volumes:
  - name: storagesecret
    secret: 
	  secretName: demo-secret
