---
# Molecule play
system_packages_for_python_venv:
  - python3-pip
  - build-essential
  - libssl-dev
  - libffi-dev
  - python3-dev
  - python3-venv
molecule_packages:
  - ansible
  - molecule
  - molecule-docker
venv_path: ~/virtual_env

# Docker play
system_packages_for_docker_installation:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

# Jenkins play
#
java_packages:
  - openjdk-8-jdk
jenkins_plugins:
  - ansicolor
  - git
  - github
  - workflow-aggregator
  - ws-cleanup
