namespace:
  name: monitoring

image:
  repository: nginx
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "prometheus"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: NodePort
  port: 8080
  targetPortPort: 9090
  nodePort: 30000

resources:
  requests:
    cpu: 500m
    memory: 500M
  limits:
    cpu: 1
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
