---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: pycontribs/centos:8
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "8888:80"
    priviliged: true
provisioner:
  name: ansible
verifier:
  name: ansible
