apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pd-volume-claim
spec:
  storageClassName: "standard"
  capacity:
    storage: 100G
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G
  persistentVolumeReclaimPolicy: Retain
